### PR TITLE
This is a small update to qira python plugin to enhance #126

### PR DESCRIPTION
**Pull request by Maroc-OS**
I have successfully tested that on both chrome and firefox and it works perfectly.

### CODE REVIEW

**Comment by Maroc-OS** [comment]
Don't forget the IDA keys for the plugins:

**Alt+X** for the binary plugin.
**Alt+F5** for the python one.

**Comment by Maroc-OS** [comment]
README file should be updated with all the needed infos about that subject

**Comment by Maroc-OS** [comment]
@nedwill

**Comment by nedwill** [comment]
Thanks, I'm looking at it now.

**Comment by Maroc-OS** [comment]
makes global qira_address as BADADDR, and check against BADADDR before updating.

the plugin was not checking against BADADDR and then it could lead to some problems.

**Comment by Maroc-OS** [comment]
Humm i have just saw that the data address also needs some checks.

**Comment by Maroc-OS** [comment]
@nedwill look at gitter.

**Comment by Maroc-OS** [comment]
i have added some debug options to make it easy for testers and for next PUSHs

**Comment by geohot** [comment]
Diff is unreadable due to formatting changes. If you fix I can look

**Comment by geohot** [comment]
Any chance this gets done? Otherwise I sadly have to close.

**Comment by Maroc-OS** [comment]
Hello, after 3 years :) you've already merged must of this manually, the rest is not a big deal, since qira got lot of updates. this needs to be rebased. i will try to download new qira this week and push ASAP

**Pull request closed without merging**
